# templates/deployment.yaml
# Defines the Kubernetes Deployment for the Prometheus Operator.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-operator-community.fullname" . }}
  labels:
    {{- include "prometheus-operator-community.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-operator-community.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prometheus-operator-community.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "prometheus-operator-community.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.operator.securityContext | nindent 8 }}
      containers:
        - name: prometheus-operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - "--kubelet-service=kube-system/kubelet" # Default Kubelet service name in kube-system
            - "--log-level=info"
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}