# templates/serviceaccount.yaml
# Defines the Kubernetes ServiceAccount for the Prometheus Operator.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-operator-community.serviceAccountName" . }}
  labels:
    {{- include "prometheus-operator-community.labels" . | nindent 4 }}
---